# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 024a818dd12ab35d656877185af250679804199f2c2e3b767a87c115908962c4130e988e3614b290f6709a8cd28897486a66be3a876d225b4be9b0b7add8d792

test:
  secret_key_base: 25ecf0bb366f7e6e1502e853d7cf7c9f30498e5d3f3a04b4949546d216ad201d7ce1f7aef4fc0aa12c443144b931831b54047db7b72e30205af0c7947240a826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
